version: '3.8'

services:
  web:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/app
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: overtime_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 0000
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

volumes:
  dbdata:
