version: '3.8'

services:
  web:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:0000@host.docker.internal:3306/overtime_db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: overtime_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 0000
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
